{% set version = '13.0.0.r560.g3197fc7d6-1' %}

package:
  name: winpthreads-split
  version: {{ version.replace("-", ".") }}

source:
  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-libwinpthread-git-{{ version }}-any.pkg.tar.zst
      # archive since the package link above expires when new versions appear.
      # NEED TO UPDATE with new archieve:
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-libwinpthread-git-{{ version }}-any.pkg.tar.zst
    sha256: c1a84fa9f0f3f1dc26c5e9ccc0aae184806985b06dde0984b0521d89e387fe2b
    folder: binary-libwinpthread

  - url:
      - https://repo.msys2.org/mingw/clangarm64/mingw-w64-clang-aarch64-libwinpthread-git-{{ version }}-any.pkg.tar.zst
      # archive since the package link above expires when new versions appear.
      # NEED TO UPDATE with new archieve:
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-libwinpthread-git-{{ version }}-any.pkg.tar.zst
    sha256: 26500bd654d19e729402e68d38d55b03e09ebc9302d67c2b473c69e39cfe435a
    folder: binary-libwinpthread-arm64

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-winpthreads-git-{{ version }}-any.pkg.tar.zst
      # archive since the package link above expires when new versions appear.
      # NEED TO UPDATE with new archieve:
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-winpthreads-git-{{ version }}-any.pkg.tar.zst
    sha256: c66e4198ad82ba9b14c1e91759709f87fbd14d4bc361e5d6cf2683785f726bfb
    folder: binary-winpthreads

  - url:
      - https://repo.msys2.org/mingw/clangarm64/mingw-w64-clang-aarch64-winpthreads-git-{{ version }}-any.pkg.tar.zst
      # archive since the package link above expires when new versions appear.
      # NEED TO UPDATE with new archieve:
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-winpthreads-git-{{ version }}-any.pkg.tar.zst
    sha256: 2fdc23be27336e820ffd24556db433a34a5db57c1d9da01eaf3ad0d213dd0887
    folder: binary-winpthreads-arm64

  - url:
      # archive them for license compliance
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-{{ version }}.src.tar.gz
      # NEED TO UPDATE with new archieve:
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-winpthreads-git-{{ version }}.src.tar.gz
    sha256: 7cb3d654d8969013231c51417640c3558f9c7a4b039a4fa1ea11c660445422c7
    folder: src-winpthread

build:
  number: 0
  skip: True  # [not win]

outputs:  
  - name: libwinpthread
    script: install_libwinpthread.bat
    files:
      - Library/bin/libwinpthread-1.dll
    requirements:
      run:
      run_constrained:
        - msys2-conda-epoch <0.0a0
        - pthreads-win32 <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_BIN%\libwinpthread-1.dll exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: MIT
      license_file: binary-libwinpthread/ucrt64/share/licenses/libwinpthread/
      summary: DLLs for MinGW-w64 winpthreads library

  - name: winpthreads
    script: install_winpthreads.bat
    files:
      - Library/lib
      - Library/include
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
      host:
        - {{ pin_subpackage("libwinpthread", exact=True) }}
      run:
        - {{ pin_subpackage("libwinpthread", exact=True) }}
      run_constrained:
        - msys2-conda-epoch <0.0a0
        - pthreads-win32 <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_INC%\pthread.h exit 1
        - if not exist %LIBRARY_INC%\sched.h exit 1
        - if not exist %LIBRARY_LIB%\libpthread.dll.a exit 1
        - if not exist %LIBRARY_LIB%\pthread.lib exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: MIT
      license_file: binary-libwinpthread/ucrt64/share/licenses/libwinpthread/
      summary: Development files for MinGW-w64 winpthreads library

about:
  home: https://mingw-w64.sourceforge.io/
  license: MIT
  license_file: binary-libwinpthread/ucrt64/share/licenses/libwinpthread/
  summary: |
    Repackaged winpthreads library

extra:
  feedstock-name: winpthreads
  recipe-maintainers:
    - isuruf
